//! ISO 4217 currencies: each code and the number of digits after its decimal point, as
//! published 2026-09-17. A money value is kept in minor units: 850 GBP is £8.50, 850
//! JPY is ¥850. Generated from the standard's list; codes without minor units (gold, funds)
//! are left out.

const std = @import("std");

pub const Currency = struct {
    code: []const u8,
    /// Digits after the decimal point: 2 for most, 0 for JPY, 3 for KWD.
    digits: u8,
    name: []const u8,
};

pub const all = [_]Currency{
    .{ .code = "AED", .digits = 2, .name = "UAE Dirham" },
    .{ .code = "AFN", .digits = 2, .name = "Afghani" },
    .{ .code = "ALL", .digits = 2, .name = "Lek" },
    .{ .code = "AMD", .digits = 2, .name = "Armenian Dram" },
    .{ .code = "AOA", .digits = 2, .name = "Kwanza" },
    .{ .code = "ARS", .digits = 2, .name = "Argentine Peso" },
    .{ .code = "AUD", .digits = 2, .name = "Australian Dollar" },
    .{ .code = "AWG", .digits = 2, .name = "Aruban Florin" },
    .{ .code = "AZN", .digits = 2, .name = "Azerbaijan Manat" },
    .{ .code = "BAM", .digits = 2, .name = "Convertible Mark" },
    .{ .code = "BBD", .digits = 2, .name = "Barbados Dollar" },
    .{ .code = "BDT", .digits = 2, .name = "Taka" },
    .{ .code = "BHD", .digits = 3, .name = "Bahraini Dinar" },
    .{ .code = "BIF", .digits = 0, .name = "Burundi Franc" },
    .{ .code = "BMD", .digits = 2, .name = "Bermudian Dollar" },
    .{ .code = "BND", .digits = 2, .name = "Brunei Dollar" },
    .{ .code = "BOB", .digits = 2, .name = "Boliviano" },
    .{ .code = "BOV", .digits = 2, .name = "Mvdol" },
    .{ .code = "BRL", .digits = 2, .name = "Brazilian Real" },
    .{ .code = "BSD", .digits = 2, .name = "Bahamian Dollar" },
    .{ .code = "BTN", .digits = 2, .name = "Ngultrum" },
    .{ .code = "BWP", .digits = 2, .name = "Pula" },
    .{ .code = "BYN", .digits = 2, .name = "Belarusian Ruble" },
    .{ .code = "BZD", .digits = 2, .name = "Belize Dollar" },
    .{ .code = "CAD", .digits = 2, .name = "Canadian Dollar" },
    .{ .code = "CDF", .digits = 2, .name = "Congolese Franc" },
    .{ .code = "CHE", .digits = 2, .name = "WIR Euro" },
    .{ .code = "CHF", .digits = 2, .name = "Swiss Franc" },
    .{ .code = "CHW", .digits = 2, .name = "WIR Franc" },
    .{ .code = "CLF", .digits = 4, .name = "Unidad de Fomento" },
    .{ .code = "CLP", .digits = 0, .name = "Chilean Peso" },
    .{ .code = "CNY", .digits = 2, .name = "Yuan Renminbi" },
    .{ .code = "COP", .digits = 2, .name = "Colombian Peso" },
    .{ .code = "COU", .digits = 2, .name = "Unidad de Valor Real" },
    .{ .code = "CRC", .digits = 2, .name = "Costa Rican Colon" },
    .{ .code = "CUP", .digits = 2, .name = "Cuban Peso" },
    .{ .code = "CVE", .digits = 2, .name = "Cabo Verde Escudo" },
    .{ .code = "CZK", .digits = 2, .name = "Czech Koruna" },
    .{ .code = "DJF", .digits = 0, .name = "Djibouti Franc" },
    .{ .code = "DKK", .digits = 2, .name = "Danish Krone" },
    .{ .code = "DOP", .digits = 2, .name = "Dominican Peso" },
    .{ .code = "DZD", .digits = 2, .name = "Algerian Dinar" },
    .{ .code = "EGP", .digits = 2, .name = "Egyptian Pound" },
    .{ .code = "ERN", .digits = 2, .name = "Nakfa" },
    .{ .code = "ETB", .digits = 2, .name = "Ethiopian Birr" },
    .{ .code = "EUR", .digits = 2, .name = "Euro" },
    .{ .code = "FJD", .digits = 2, .name = "Fiji Dollar" },
    .{ .code = "FKP", .digits = 2, .name = "Falkland Islands Pound" },
    .{ .code = "GBP", .digits = 2, .name = "Pound Sterling" },
    .{ .code = "GEL", .digits = 2, .name = "Lari" },
    .{ .code = "GHS", .digits = 2, .name = "Ghana Cedi" },
    .{ .code = "GIP", .digits = 2, .name = "Gibraltar Pound" },
    .{ .code = "GMD", .digits = 2, .name = "Dalasi" },
    .{ .code = "GNF", .digits = 0, .name = "Guinean Franc" },
    .{ .code = "GTQ", .digits = 2, .name = "Quetzal" },
    .{ .code = "GYD", .digits = 2, .name = "Guyana Dollar" },
    .{ .code = "HKD", .digits = 2, .name = "Hong Kong Dollar" },
    .{ .code = "HNL", .digits = 2, .name = "Lempira" },
    .{ .code = "HTG", .digits = 2, .name = "Gourde" },
    .{ .code = "HUF", .digits = 2, .name = "Forint" },
    .{ .code = "IDR", .digits = 2, .name = "Rupiah" },
    .{ .code = "ILS", .digits = 2, .name = "New Israeli Sheqel" },
    .{ .code = "INR", .digits = 2, .name = "Indian Rupee" },
    .{ .code = "IQD", .digits = 3, .name = "Iraqi Dinar" },
    .{ .code = "IRR", .digits = 2, .name = "Iranian Rial" },
    .{ .code = "ISK", .digits = 0, .name = "Iceland Krona" },
    .{ .code = "JMD", .digits = 2, .name = "Jamaican Dollar" },
    .{ .code = "JOD", .digits = 3, .name = "Jordanian Dinar" },
    .{ .code = "JPY", .digits = 0, .name = "Yen" },
    .{ .code = "KES", .digits = 2, .name = "Kenyan Shilling" },
    .{ .code = "KGS", .digits = 2, .name = "Som" },
    .{ .code = "KHR", .digits = 2, .name = "Riel" },
    .{ .code = "KMF", .digits = 0, .name = "Comorian Franc" },
    .{ .code = "KPW", .digits = 2, .name = "North Korean Won" },
    .{ .code = "KRW", .digits = 0, .name = "Won" },
    .{ .code = "KWD", .digits = 3, .name = "Kuwaiti Dinar" },
    .{ .code = "KYD", .digits = 2, .name = "Cayman Islands Dollar" },
    .{ .code = "KZT", .digits = 2, .name = "Tenge" },
    .{ .code = "LAK", .digits = 2, .name = "Lao Kip" },
    .{ .code = "LBP", .digits = 2, .name = "Lebanese Pound" },
    .{ .code = "LKR", .digits = 2, .name = "Sri Lanka Rupee" },
    .{ .code = "LRD", .digits = 2, .name = "Liberian Dollar" },
    .{ .code = "LSL", .digits = 2, .name = "Loti" },
    .{ .code = "LYD", .digits = 3, .name = "Libyan Dinar" },
    .{ .code = "MAD", .digits = 2, .name = "Moroccan Dirham" },
    .{ .code = "MDL", .digits = 2, .name = "Moldovan Leu" },
    .{ .code = "MGA", .digits = 2, .name = "Malagasy Ariary" },
    .{ .code = "MKD", .digits = 2, .name = "Denar" },
    .{ .code = "MMK", .digits = 2, .name = "Kyat" },
    .{ .code = "MNT", .digits = 2, .name = "Tugrik" },
    .{ .code = "MOP", .digits = 2, .name = "Pataca" },
    .{ .code = "MRU", .digits = 2, .name = "Ouguiya" },
    .{ .code = "MUR", .digits = 2, .name = "Mauritius Rupee" },
    .{ .code = "MVR", .digits = 2, .name = "Rufiyaa" },
    .{ .code = "MWK", .digits = 2, .name = "Malawi Kwacha" },
    .{ .code = "MXN", .digits = 2, .name = "Mexican Peso" },
    .{ .code = "MXV", .digits = 2, .name = "Mexican Unidad de Inversion (UDI)" },
    .{ .code = "MYR", .digits = 2, .name = "Malaysian Ringgit" },
    .{ .code = "MZN", .digits = 2, .name = "Mozambique Metical" },
    .{ .code = "NAD", .digits = 2, .name = "Namibia Dollar" },
    .{ .code = "NGN", .digits = 2, .name = "Naira" },
    .{ .code = "NIO", .digits = 2, .name = "Cordoba Oro" },
    .{ .code = "NOK", .digits = 2, .name = "Norwegian Krone" },
    .{ .code = "NPR", .digits = 2, .name = "Nepalese Rupee" },
    .{ .code = "NZD", .digits = 2, .name = "New Zealand Dollar" },
    .{ .code = "OMR", .digits = 3, .name = "Rial Omani" },
    .{ .code = "PAB", .digits = 2, .name = "Balboa" },
    .{ .code = "PEN", .digits = 2, .name = "Sol" },
    .{ .code = "PGK", .digits = 2, .name = "Kina" },
    .{ .code = "PHP", .digits = 2, .name = "Philippine Peso" },
    .{ .code = "PKR", .digits = 2, .name = "Pakistan Rupee" },
    .{ .code = "PLN", .digits = 2, .name = "Zloty" },
    .{ .code = "PYG", .digits = 0, .name = "Guarani" },
    .{ .code = "QAR", .digits = 2, .name = "Qatari Rial" },
    .{ .code = "RON", .digits = 2, .name = "Romanian Leu" },
    .{ .code = "RSD", .digits = 2, .name = "Serbian Dinar" },
    .{ .code = "RUB", .digits = 2, .name = "Russian Ruble" },
    .{ .code = "RWF", .digits = 0, .name = "Rwanda Franc" },
    .{ .code = "SAR", .digits = 2, .name = "Saudi Riyal" },
    .{ .code = "SBD", .digits = 2, .name = "Solomon Islands Dollar" },
    .{ .code = "SCR", .digits = 2, .name = "Seychelles Rupee" },
    .{ .code = "SDG", .digits = 2, .name = "Sudanese Pound" },
    .{ .code = "SEK", .digits = 2, .name = "Swedish Krona" },
    .{ .code = "SGD", .digits = 2, .name = "Singapore Dollar" },
    .{ .code = "SHP", .digits = 2, .name = "Saint Helena Pound" },
    .{ .code = "SLE", .digits = 2, .name = "Leone" },
    .{ .code = "SOS", .digits = 2, .name = "Somali Shilling" },
    .{ .code = "SRD", .digits = 2, .name = "Surinam Dollar" },
    .{ .code = "SSP", .digits = 2, .name = "South Sudanese Pound" },
    .{ .code = "STN", .digits = 2, .name = "Dobra" },
    .{ .code = "SVC", .digits = 2, .name = "El Salvador Colon" },
    .{ .code = "SYP", .digits = 2, .name = "Syrian Pound" },
    .{ .code = "SZL", .digits = 2, .name = "Lilangeni" },
    .{ .code = "THB", .digits = 2, .name = "Baht" },
    .{ .code = "TJS", .digits = 2, .name = "Somoni" },
    .{ .code = "TMT", .digits = 2, .name = "Turkmenistan New Manat" },
    .{ .code = "TND", .digits = 3, .name = "Tunisian Dinar" },
    .{ .code = "TOP", .digits = 2, .name = "Pa’anga" },
    .{ .code = "TRY", .digits = 2, .name = "Turkish Lira" },
    .{ .code = "TTD", .digits = 2, .name = "Trinidad and Tobago Dollar" },
    .{ .code = "TWD", .digits = 2, .name = "New Taiwan Dollar" },
    .{ .code = "TZS", .digits = 2, .name = "Tanzanian Shilling" },
    .{ .code = "UAH", .digits = 2, .name = "Hryvnia" },
    .{ .code = "UGX", .digits = 0, .name = "Uganda Shilling" },
    .{ .code = "USD", .digits = 2, .name = "US Dollar" },
    .{ .code = "USN", .digits = 2, .name = "US Dollar (Next day)" },
    .{ .code = "UYI", .digits = 0, .name = "Uruguay Peso en Unidades Indexadas (UI)" },
    .{ .code = "UYU", .digits = 2, .name = "Peso Uruguayo" },
    .{ .code = "UYW", .digits = 4, .name = "Unidad Previsional" },
    .{ .code = "UZS", .digits = 2, .name = "Uzbekistan Sum" },
    .{ .code = "VED", .digits = 2, .name = "Bolívar Soberano" },
    .{ .code = "VES", .digits = 2, .name = "Bolívar Soberano" },
    .{ .code = "VND", .digits = 0, .name = "Dong" },
    .{ .code = "VUV", .digits = 0, .name = "Vatu" },
    .{ .code = "WST", .digits = 2, .name = "Tala" },
    .{ .code = "XAD", .digits = 2, .name = "Arab Accounting Dinar" },
    .{ .code = "XAF", .digits = 0, .name = "CFA Franc BEAC" },
    .{ .code = "XCD", .digits = 2, .name = "East Caribbean Dollar" },
    .{ .code = "XCG", .digits = 2, .name = "Caribbean Guilder" },
    .{ .code = "XOF", .digits = 0, .name = "CFA Franc BCEAO" },
    .{ .code = "XPF", .digits = 0, .name = "CFP Franc" },
    .{ .code = "YER", .digits = 2, .name = "Yemeni Rial" },
    .{ .code = "ZAR", .digits = 2, .name = "Rand" },
    .{ .code = "ZMW", .digits = 2, .name = "Zambian Kwacha" },
    .{ .code = "ZWG", .digits = 2, .name = "Zimbabwe Gold" },
};

/// The currency with this code, or null when ISO 4217 has none.
pub fn find(code: []const u8) ?Currency {
    std.debug.assert(all.len > 100);

    if (code.len != 3) {
        return null;
    }

    for (all) |currency| {
        if (std.mem.eql(u8, currency.code, code)) {
            return currency;
        }
    }

    return null;
}

test "currencies: codes and their digits" {
    try std.testing.expectEqual(@as(u8, 2), find("GBP").?.digits);
    try std.testing.expectEqual(@as(u8, 0), find("JPY").?.digits);
    try std.testing.expectEqual(@as(u8, 3), find("KWD").?.digits);
    try std.testing.expect(find("XAU") == null);
    try std.testing.expect(find("ZZZ") == null);
    try std.testing.expect(find("gbp") == null);
}
